// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/** Shared log for GAS-lite combat scaffolding */
DECLARE_LOG_CATEGORY_EXTERN(LogCombatGAS, Log, All);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Attack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Dodge);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Dodge_IFrames);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Noetic_ExistenceShift);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Noetic_MemoryBurn);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Noetic_TemporalEcho);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Noetic_AetherBlight);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_VigilStep);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_CenserLunge);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_Fold);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_AshenRecitation);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_CensureLance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_Unwriting);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_SecondBreath);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_Palindrome);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Noetic_EffigyVow);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Noetic_VigilWard);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Noetic_SecondBreath);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Noetic_Purge);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_AeterniiCorruption);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_AeterniiHealth);
